### ISSUE TITLE
How did you implement h-hop enclosing subgraph

### ISSUE THREAD

**Issue by SusuXu** [caojiangxia/BiGI#4]
Hi, thanks for your repo. I wonder how you implemented the h-hop enclosing subgraph. Now I only see you set a mask, but how you got the mask? Thanks

**Comment by caojiangxia** [comment]
If h>1, we preprocess the fixed number nodes h-hop subgraph in Dataloder (same with IGMC method) and uses the module (AttDGI) to calculate.

However, 1-hop is a special case, we can calculate it without any preprocessing in a similar way to GAT, see the myDGI module.

**Comment by SusuXu** [comment]
Thanks for your response. Where did you specify h in the code/Dataloader? I couldn't find it. Meanwhile, how did you select h? Thanks.

**Comment by caojiangxia** [comment]
The released code is focused on h = 1. Add some codes in preprocess function of Dataloader can extend to h > 1.
