### ISSUE TITLE
作者你好，想问下DMGI单次run只能得到一类节点的embedding，是做了两次run吗？

### ISSUE THREAD

**Issue by Yonggie** [caojiangxia/BiGI#6]
如果是两次run，metapath的选取是怎样的呢？想知道DMGI实验更加具体一点的细节。
感谢作者的回复。

original question: 
For DMGI model, we can get single type of node embedding per run of DMGI, but there are two kinds of node in bipartite graph. In experiment, DMGI baseline conducted item AND user node for performance testing. So my question is to know more about the metapath selection in DMGI baseline and confirm if it runs twice to get both user and item embeddings of DMGI.

Thank you so much in advance.

**Comment by caojiangxia** [comment]
你好，我最近一直没登github，现在才看到。。。

对于DMGI，对于每个二部图，我们之前是跑了一次得到embedding的 （id是user在前，item在后）。但是后面的rec和lp任务是把这些存起来的embedding作为static_feature再训练一个pair wise的有监督模型去适配下游任务。

关于原路径的选择，我是在DMGI的预处理代码上进行了修改得到UV和VU，之后生成了几个邻接矩阵(同质的1-hop和2-hop)，对于user：UVU, UVUVU 对于item：VUV, VUVUV，（相同路径长度的处理完之后，可以放到一个邻接矩阵里）。其他的也没有再尝试了，这个原路径的选择和Metapath2vec一样。
